### ISSUE TITLE
Filtering on Updates Available

### ISSUE THREAD

**Issue by herbkk** [darthnorse/dockmon#115]
When I select all containers and do a manual Check Updates action, some updates are found, and shown by an icon (update available). When you apply the filter Updates Available, these containers are not shown, the list is empty. Only after some time (> 1 min) these are shown when using the filter.

Is it possible that the filters can be directly applied, after doing an manual update check?

I'm using the 2.2.2. version.

**Comment by darthnorse** [comment]
Confirmed, there's a 60 second cache that isn't invalidated. Fixed in v2.2.3 which will be out today

**Comment by herbkk** [comment]
I checked this issue in 2.2.3 and the issue is still there: the update only shows in the filter after 60 secs.


<img width="1910" height="456" alt="Image" src="https://github.com/user-attachments/assets/dc7913f9-b664-4827-8002-21d311b52922" />

**Comment by darthnorse** [comment]
My bad, I missed a place. I was able to reproduce this myself and after a second fix it works for me. Will release a v2.2.4 soon.

**Comment by herbkk** [comment]
Thanks, I doublechecked on 2.2.4 . The filtering on Updates available is now working. However, if you add the status Stopped and Running to the filter, after selecting Updates Available, the status Stopped and Running do not show. I guess it's a minor issue, with low prio....

<img width="767" height="221" alt="Image" src="https://github.com/user-attachments/assets/2d0bda49-ff10-4d37-8da2-ca959383a5f9" />

**Comment by darthnorse** [comment]
I'm not sure exactly what you mean. The way it works is

(Running OR Stopped) AND HasUpdates

If you just select Stopped it would be "Show me all containers are stopped and have updates". I just tested this and it works exactly like designed.

**Comment by herbkk** [comment]
Check, I thought it was meant as Running OR Stopped OR Update Available.
